name: Automated Layout Pipeline

on:
    push:
        branches: ["test_pipeline"]

jobs:
    build-and-generate:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t layout-pipeline .

            - name: Run Tests with pytest
              run: |
                echo "=== [Test] Run pytest inside Docker ==="
                docker run --rm \
                  --network=host \
                  --user $(id -u):$(id -g) \
                  -v ${{ github.workspace }}:/app \
                  layout-pipeline uv run pytest -v -s practice/test_custom_layouts.py
            - name: Generate Layouts
              run: |
                mkdir -p output

                echo "=== [Debug] Run Photodetector.py ==="
                docker run --rm \
                  --network=host \
                  --user $(id -u):$(id -g) \
                  -v ${{ github.workspace }}/output:/app/output \
                  layout-pipeline uv run --no-cache practice/layouts/Photodetector.py

                echo "=== [Debug] file list in the output folder ==="
                ls -al output
            - name: Backup Files to Local Storage
              run: |
                mkdir -p /home/yoseobi/gds_results

                cp output/*.gds /home/yoseobi/gds_results/